site_name: cm2py Documentation
site_url: https://cm2py.skmgeek.com
theme:
  name: material

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: "index.md"
  - Getting Started: "getting-started.md"
  - About:
      - "License": "license.md"
